name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build -t docker.pkg.github.com/Yorkerrr/craiglist/craiglist:latest .
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/Yorkerrr/craiglist/craiglist:latest
